// <auto-generated />
using LodestarHealthDataApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace LodestarHealthDataApi.Migrations
{
    [DbContext(typeof(LodestarAPIContext))]
    partial class LodestarAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("LodestarHealthDataApi.Models.Facility", b =>
                {
                    b.Property<int>("FacilityId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CY_Discharges");

                    b.Property<long>("Current_Assets");

                    b.Property<long>("Current_Liabilities");

                    b.Property<double>("Current_Year_Commercial_Market_Share");

                    b.Property<double>("Current_Year_Market_Share");

                    b.Property<long>("EBITDAR");

                    b.Property<long>("Estimated_CM");

                    b.Property<long>("Estimated_EBITDA");

                    b.Property<long>("Estimated_NR");

                    b.Property<string>("Facility_Name");

                    b.Property<long>("Fund_Balance");

                    b.Property<double>("Household_Income");

                    b.Property<double>("Lat");

                    b.Property<int>("Likelihood_To_Recommend");

                    b.Property<double>("Long");

                    b.Property<int>("Overall_Hospital_Linear_Mean_Score");

                    b.Property<string>("Quality_Complications_Deaths");

                    b.Property<string>("Quality_Hosp_Acq_Infections");

                    b.Property<string>("Quality_Readmissions");

                    b.Property<string>("System_Affiliation_Name");

                    b.Property<double>("Total_2017_22_Pop_Growth");

                    b.Property<long>("Total_Liabilities");

                    b.HasKey("FacilityId");

                    b.ToTable("Facility");
                });
#pragma warning restore 612, 618
        }
    }
}
